version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: urlshortenerdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "url_shortener"
    ports:
      - "5432:5432"