auth:
  jwt_secret: ${JWT_SECRET}
  jwt_expiration_in_hours: 10

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

spring:
  application:
    name: urlshorter

  datasource:
    url: ${DB_HOST}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: false